<!DOCTYPE html>
<html>

<head>
    <title>Thriposha Distribution Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            color: #2b7c85;
            margin-bottom: 5px;
        }

        .header .subtitle {
            color: #666;
            font-size: 14px;
        }

        .report-info {
            margin-bottom: 20px;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #2b7c85;
            color: white;
            padding: 8px;
            text-align: left;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        .summary {
            margin-top: 30px;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }

        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #666;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Thriposha Distribution Report</h1>
        <div class="subtitle">Generated on {{ now()->format('M d, Y h:i A') }}</div>
    </div>

    <div class="report-info">
        <p><strong>Report Period:</strong> {{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</p>
        @if ($typeFilter)
            <p><strong>Type Filter:</strong> {{ ucfirst($typeFilter) }} Thriposha</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Quantity</th>
                <th>Recipient</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @forelse($distributions as $distribution)
                <tr>
                    <td>{{ $distribution->date->format('M d, Y') }}</td>
                    <td>{{ ucfirst($distribution->type) }}</td>
                    <td>{{ $distribution->quantity }} packs</td>
                    <td>{{ $distribution->recipient }}</td>
                    <td>{{ $distribution->notes ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No distributions found for the selected period</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if ($distributions->isNotEmpty())
        <div class="summary">
            <h3>Summary</h3>
            <p><strong>Total Distributions:</strong> {{ $distributions->count() }}</p>
            <p><strong>Total Baby Thriposha Distributed:</strong> {{ $babyTotal }} packs</p>
            <p><strong>Total Mother Thriposha Distributed:</strong> {{ $motherTotal }} packs</p>
            <p><strong>Overall Total Distributed:</strong> {{ $babyTotal + $motherTotal }} packs</p>
        </div>
    @endif

    <div class="footer">
        <p>Generated by: {{ Auth::user()->name ?? 'System' }}</p>
    </div>
</body>

</html>
